apiVersion: v1
kind: ConfigMaps
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  food: {{ .Values.favorite.food | quote | upper }}
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  {{ if and .Values.isAdmin .Values.isAllowed }}
  allowed: {{ printf "true" }}
  {{ else }}
  allowed: {{ cat "true" "folks" }}
  {{ end }}
